# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    runs-on: ubuntu-latest
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres:15-alpine
          # Provide the password for postgres
          env:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: root
            POSTGRES_DB: simple_bank
            
          ports:
            # Maps tcp port 5432 on service container to the host
            - 5432:5432

          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: installing migrate to perform migration steps
      run: |
        wget -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz
        tar xvfz migrate.linux-amd64.tar.gz
        sudo mv migrate /usr/bin
        

    - name: migrating db schema
      run: make migrateup

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
